/userdata/dxu/anaconda3/bin/python3: can't open file '/userdata/dxu/project_np/analysis/preproc/np_sglx_catgt_NP36_B1.py': [Errno 2] No such file or directory
CatGT command:
['bash', '/userdata/dxu/pkg/NP/CatGT-linux/runit.sh', '-dir=/datastore_spirit/human/Neuropixels/NP36 -run=NP36_B1 -g=0,0 -t=0,0 -zerofillmax=0 -prb=0 -ap -lf -ni -gblcar -gfix=0.40,0.10,0.02 -SY=0,384,6,500 -XA=0,1,3,500 -prb_fld -out_prb_fld -dest=/userdata/dxu/project_np/preproc/sglx/NP36']
CatGT command:
['bash', '/userdata/dxu/pkg/NP/CatGT-linux/runit.sh', '-dir=/datastore_spirit/human/Neuropixels/NP36 -run=NP36_B2 -g=0,0 -t=0,0 -zerofillmax=0 -prb=0 -ap -lf -ni -gblcar -gfix=0.40,0.10,0.02 -SY=0,384,6,500 -XA=0,1,3,500 -prb_fld -out_prb_fld -dest=/userdata/dxu/project_np/preproc/sglx/NP36_B2']
